# Gitlab ci/cd file configuration 
image: sebastienviardot/pcsef_riscv:20250708
stages:
    - verif
student_test:
    stage: verif
    tags:
        - docker
    script:
        - cd src && make kernel.bin && curl --request POST --form "token=${TRIGGER_TOKEN}" --form "ref=main" "${CI_API_V4_URL}/projects/${EVAL_PROJECT_ID}/trigger/pipeline"
    artifacts:
        paths:
            - ./src/**/*.c
            - ./src/**/*.h
            - ./src/**/*.S
    only:
        - main


